Filmsket/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls")),
]

main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
    path("filmsket/", views.intro, name = "intro"),
    path("", views.homepage, name = "homepage"),
    path("register/", views.register, name = "register"),
    path("logout/", views.logout_request, name = "logout"),
    path("login/", views.login_request, name = "login"),
    path("<int:id>/", views.index, name="index"),
    path("create/", views.create, name="create"),
    path("<int:id>/search_results/", views.search_results, name='search_results'),
    path("<int:id>/film_info/", views.film_info, name='film'),
    path("<int:id>/rename/", views.rename, name='rename'),
]

main/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User
# Create your models here.


class Basket(models.Model):
    BasketGenre = models.CharField(max_length=200)
    user = models.ForeignKey(User, default=1, on_delete=models.CASCADE, related_name="basket", null=True)

    class Meta:
        verbose_name_plural = "Baskets"

    def __str__(self):
        return self.BasketGenre

class Film(models.Model):
    summary = models.CharField(max_length=900, null=True)
    poster = models.CharField(max_length=900)
    url = models.CharField(max_length=200)
    
    BasketGenre = models.ForeignKey(Basket, default=1, verbose_name="basket", on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name

class Result(models.Model):
    result = models.CharField(max_length=900)
    url= models.CharField(max_length=200)
    Num = models.IntegerField()
    poster = models.CharField(max_length=900)

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

class CreateNewBasket(forms.Form):
    name = forms.CharField(label="Basket Name", max_length=200)

class RenameBasket(forms.Form):
    new_name = forms.CharField(label="New Basket Name", max_length=200)

main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Film, Basket, Result
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from .forms import NewUserForm, CreateNewBasket, RenameBasket
import imdb
import urllib.request
import re
# Create your views here.


def film_info(request, id):
    film = Film.objects.get(id=id)
    
    description = film.summary
    li = list(description.split("\n"))
    
    return render(request, "main/film.html", {"Film":film, "summary":li[2:]})

def search_results(request, id):
    moviesDB = imdb.IMDb()
    if request.method=="POST":
        
        if request.POST.get("Add"):
            results = Result.objects.filter(Num=id)
            search_result = results[len(results) - 1 ]
            
            basket = Basket.objects.get(id=id)
            basket.film_set.create(summary=search_result.result, poster=search_result.poster, url=search_result.url)
            Result.objects.all().delete()
            
            return redirect("main:index", id=id)
        
        search = request.POST.get('search')
        
        movies = moviesDB.search_movie(search)[0]
        movie_id = movies.getID()
        movie = moviesDB.get_movie(movie_id)

        title = (movie["title"] + " " + str(movie["year"]) + " Trailer").replace(" ", "+")
        html = urllib.request.urlopen("https://www.youtube.com/results?search_query=" + title)
        results = re.findall(r"watch\?v=(\S{11})", html.read().decode())
        url = "https://www.youtube.com/embed/" + results[0]

        r = Result(result=movie.summary(), url=url, Num=id, poster=movie['full-size cover url'])
        r.save()
        
        description = r.result
        li = list(description.split("\n"))
        
        return render(request, "main/search_results.html", {"result":r, "id":id, "summary":li[2:]})

def create(request):
    if not request.user.is_anonymous:
        if request.method == "POST":
            form = CreateNewBasket(request.POST)

            if form.is_valid():
                new_basket = form.cleaned_data["name"]
                c = Basket(BasketGenre=new_basket)
                c.save()
                request.user.basket.add(c)
                messages.success(request, f"New Film Basket Made: {new_basket}")
                return redirect("main:homepage")
    
        form = CreateNewBasket()
        return render(request, "main/create.html", {"form":form})
    
    return redirect("main:homepage")

def rename(request, id):
    basket = Basket.objects.get(id=id)
    if not request.user.is_anonymous:
        if basket in request.user.basket.all():
            if request.method == "POST":
                form = RenameBasket(request.POST)
                    
                if form.is_valid():
                    name = form.cleaned_data["new_name"]
                    basket = Basket.objects.get(id=id)
                    basket.BasketGenre = name
                    basket.save()
                    messages.success(request, f"New Film Basket Name: {name}")
                    return redirect("main:homepage")
        
            form = RenameBasket()
            return render(request, "main/rename.html", {"form":form})
        
        return redirect("main:homepage")

    return redirect("main:homepage")

def index(request, id): 
    baskets = Basket.objects.get(id=id)
    films = baskets.film_set.all()
    
    if not request.user.is_anonymous:
        if baskets in request.user.basket.all():
            
            if request.method=="POST": 
                for i in films:  
                    if request.POST.get("c" + str(i.id)) == "clicked":
                        i.delete()

                baskets = Basket.objects.get(id=id)
                films = baskets.film_set.all()
                    
                return render(request, "main/basket.html", {"films":films , "id":id}) 

            return render(request, "main/basket.html", {"films":films, "id":id})

        return render(request,"main/baskets.html",{})
    else:
        return redirect("main:homepage")
    

def homepage(request):
    if not request.user.is_anonymous:
        if request.method=="POST":
            for b in request.user.basket.all():
                if request.POST.get("c" + str(b.id)) == "clicked":
                    b.delete()
                    return redirect("main:homepage")
        
        return render(request, 
                  "main/baskets.html", 
                  {})

    return render(request, 
                  "main/Intro.html", 
                  {})

def intro(request):
    if request.user.is_anonymous:
        return render(request, 
                  "main/Intro.html", 
                  {})
    
    return render(request, 
                  "main/baskets.html", 
                  {})

def register(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f"New Account Created: {username}")
            login(request, user)
            messages.info(request, f"You are now logged in as {username}")
            return redirect("main:homepage")
        else:
            for msg in form.error_messages:
                print(form.error_messages[msg])             

    form = NewUserForm
    return render(request, 
           "main/register.html", 
           context={"form":form})

def logout_request(request):
    logout(request)
    messages.info(request, "Logged out successfully!")
    return redirect("main:homepage")

def login_request(request):
    if request.method == "POST":
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"You are now logged in as {username}")
                return redirect("main:homepage")
            else:
                messages.error(request, "Invalid username or password")
        else:
            messages.error(request, "Invalid username or password")
    
    form = AuthenticationForm()
    return render(request, "main/login.html", {"form":form})
        

main/templates/main/Intro.html
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <!-- Compiled and minified CSS -->
    <link href="{% static "main/css/materialize.css" %}" rel="stylesheet">
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>

<body  class="deep-purple darken-4">

{% include "main/includes/messages.html" %}
    
    <div class="container">
        <a href="/"><h2  class="purple-text text-accent-2">Filmsket</h2></a>
        <p style="font-size:160%;" class="purple-text text-accent-2">Utilizes <a href="https://imdbpy.readthedocs.io/en/latest/" class="blue-text text-accent-4">IMDbPY</a> to provide custom interactive To-Watch Lists</P> 
        <a href="/register" class="waves-effect waves-light btn-large purple-text text-accent-2" style="background-color:blue">Get Started</a>
        
        <p></P>    

        <img src="{% static 'giphy.gif' %}" >
    </div>
         
</body>

<style>
img {
    height:450px;
    width:100%;
    object-fit: scale-down;
}
}
</style>

<style>
    body{
        text-align: center;

        background-image: url("{% static 'background.jpg' %}");

        background-repeat: no-repeat;
        background-size: cover;
        background-position: center;
        } 
</style>

main/templates/main/basket.html
{% extends 'main/header.html' %}

{% block content %}

    <p>
    <nav>
        <div class="nav-wrapper">
        <form method="post" action="{% url 'main:search_results' id%}">
        {%csrf_token%}
            <div class="input-field">
                <input id="search" type="search" placeholder="Search Film" name="search" required>
                <label class="label-icon" for="search"><i class="material-icons">search</i></label>
                <i class="material-icons">close</i>
            </div>
        </form>
        </div>
    </nav>
    </p>
    
    <div class="row">
        <form method="post" action="#">
        {%csrf_token%}
            {% for f in films %}
                <div class="col s12 m6">
                <a href="{% url 'main:film' f.id %}">
                    <div class="card hoverable">
                        <div class="card-image">
                            <img class="poster" src={{f.poster}}>
                            <button class="btn-floating halfway-fab waves-effect waves-light-blue darken-4" type="submit", name="c{{f.id}}", value="clicked"><i class="material-icons purple-text text-accent-2">check</i></button>
                        </div>  
                    </div>
                </a>
                </div>
                <p></p>
                <p></p>
            {% endfor %}
        </form>
    </div>

{% endblock %}

main/templates/main/baskets.html
{% extends 'main/header.html' %}

{% block content %}

    <div class="row">
    <form method="post" action="#">
    {%csrf_token%}
        {% for b in user.basket.all  %}
            <div class="col s12 m6 l4">
                <a href="{{b.id}}", style="color:#000">
                    <div class="card hoverable" style="background-color:blue">
                        <div class="card-content">
                            <div class="card-title purple-text text-accent-2">{{b.BasketGenre}}</div>                          
                        </div>
                            <button class="waves-effect waves-light btn-small purple accent-2" style="color:blue" type="submit" name="c{{b.id}}", value="clicked">
                            <i class="material-icons middle">clear</i>
                            </button>
                            <a href="{% url 'main:rename' b.id %}" class="waves-effect waves-light btn-small purple accent-2" style="color:blue">
                            <i class="material-icons middle " >create</i>
                            </a>
                    </div>
                </a>
            </div>
        {% endfor %}
    </form>
    </div>
    <a href="/create", class="waves-effect waves-light btn purple-text text-accent-2" style="background-color:blue"><i class="material-icons left">add</i>Create Basket</a>
{% endblock %}

main/templates/main/create.html
{% extends "main/header.html" %}
{% block content %}
    <form method = "POST">
        {%csrf_token%}
        {{form.as_p}}

        <button class = "btn" style = "background-color:blue; color:red" type="submit">Create</button>
    </form>

{% endblock %}
      

main/templates/main/film.html
{% extends 'main/header.html' %}

{% block content %}

    <div class="col s12 m6">
        <div class="card purple-text text-accent-2" style="background-color:blue">
            <div class="video-container">
                <iframe width="853" height="480" src={{Film.url}} frameborder="0" allowfullscreen></iframe>
            </div>
            <div class="card-content">
            {% for s in summary %}
                <ul>
                    <li>{{s}} </li>
                </ul>
            {% endfor %}
            </div>
        </div>
    </div>

{% endblock %}
      

main/templates/main/header.html
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <!-- Compiled and minified CSS -->
    <link href="{% static "main/css/materialize.css" %}" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    
</head>

<body class="deep-purple darken-4">
    
    {% include "main/includes/navbar.html" %}

    {% include "main/includes/messages.html" %}  

    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    
</body>       

main/templates/main/home.html
{% extends "main/header.html" %}
{% block content %}
    <div class="row">
        {% for i in info%}
            <div class="col s12 m6 14">
                <div class="card blue darken-4">
                    <div class="card-content white-text">
                        <span class="card-title">{{i.name}}</span> 
                        <p>{{i.name}}</p>
                        <p>{{i.date}}</p>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}
      

main/templates/main/login.html
{% extends "main/header.html" %}
{% block content %}
    <form method = "POST">
        {%csrf_token%}
        {{form.as_p}}

        <button class = "btn" style = "background-color:blue; color:red" type="submit">Login</button>
    </form>

    <a class="purple-text text-accent-2">if you don't have an account, </a><a href="/register" class="red-text"><strong>register</strong></a><a class="purple-text text-accent-2"> for one.</a>

{% endblock %}
      

main/templates/main/register.html
{% extends "main/header.html" %}
{% block content %}
    <form method="POST" class="purple-text text-accent-2">
        {%csrf_token%}
        {{form.as_p}}

        <button class="btn purple-text text-accent-2" style="background-color:blue" type="submit">register</button>
    </form>
    
    <a class="purple-text text-accent-2">if you already have an account, </a><a href="/login" class="red-text"><strong>login</strong></a><a class="purple-text text-accent-2"> instead.<a/>
   
{% endblock %}
      

main/templates/main/rename.html
{% extends "main/header.html" %}
{% block content %}
    <form method = "POST">
        {%csrf_token%}
        {{form.as_p}}

        <button class = "btn" style = "background-color:blue; color:red" type="submit">Rename</button>
    </form>

{% endblock %}

main/templates/main/search_results.html
{% extends "main/header.html" %}
{% block content %}
<form method="post">
{%csrf_token%}
    <div class="col s12 m6">
        <div class="card purple-text text-accent-2" style="background-color:blue">
            <div class="video-container">
                <iframe width="853" height="480" src={{result.url}} frameborder="0" allowfullscreen></iframe>
            </div>
            <div class="card-content">
            {% for s in summary %}
                <ul>
                    <li> {{s}} </li>
                </ul>
            {% endfor %}
            </div>
            <button type="submit", name="Add", value="Add" class="waves-effect waves-light btn deep-purple darken-4 purple-text text-accent-2"><i class="material-icons left" >add</i>Add Film</button>
        </div>
    </div>
</form>
{% endblock %}
      